Initial release
dradis/dradis-nipper pull request #1
Opened 2020-09-11 12:35 UTC by aapomm

2020-09-14 07:54 UTC, sean-yeoh commented on lib/dradis/plugins/nipper/field_processor.rb
> +        ALLOWED_DATA_NAMES = %w{section devices}
alpha order

2020-09-14 07:55 UTC, sean-yeoh commented on lib/dradis/plugins/nipper/gem_version.rb
> +        STRING = [MAJOR, MINOR, TINY, PRE].compact.join(".")
```suggestion
        STRING = [MAJOR, MINOR, TINY, PRE].compact.join(".")
        STRING = [MAJOR, MINOR, TINY, PRE].compact.join('.')
```

2020-09-14 07:56 UTC, sean-yeoh commented on lib/nipper/evidence.rb
> +      [ :device_name, :device_type, :device_osversion ]
alpha order

2020-09-14 07:56 UTC, sean-yeoh commented on lib/nipper/issue.rb
> +        :finding, :impact, :ease, :recommendation
alpha order too

2020-09-14 09:47 UTC, sean-yeoh commented on lib/dradis/plugins/nipper/field_processor.rb
> +        def post_initialize(args={})
```suggestion
        def post_initialize(args = {})
```
spacing

2020-09-14 09:50 UTC, sean-yeoh commented on lib/dradis/plugins/nipper/field_processor.rb
> +        def value(args={})
```suggestion
        def value(args = {})
```
spacing

2020-09-14 09:57 UTC, sean-yeoh commented on lib/dradis/plugins/nipper/importer.rb
> +
```suggestion
```

2020-09-14 09:58 UTC, sean-yeoh commented on lib/dradis/plugins/nipper/importer.rb
> +    def import(params={})
```suggestion
    def import(params = {})
```
spacing

2020-09-14 10:00 UTC, sean-yeoh commented on lib/dradis/plugins/nipper/field_processor.rb
> +
```suggestion
```
remove newline

2020-09-14 10:08 UTC, sean-yeoh commented on lib/nipper/issue.rb
> +      return process_field_value(method)
```suggestion
      process_field_value(method)
```
remove extra return

2020-09-14 10:09 UTC, sean-yeoh commented on lib/nipper/issue.rb
> +        @xml.xpath("./#{translations_table[method].to_s}").first.try(:text)
```suggestion
        @xml.xpath("./#{translations_table[method]}").first.try(:text)
```
redundant `.to_s`

2020-09-14 10:09 UTC, sean-yeoh commented on lib/nipper/issue.rb
> +        @xml.xpath("./#{translations_table[base_method].to_s}").first.try(:text)
```suggestion
        @xml.xpath("./#{translations_table[base_method]}").first.try(:text)
```
redundant `.to_s`

2020-09-14 10:10 UTC, sean-yeoh commented on lib/nipper/issue.rb
> +        @xml.xpath("./#{translations_table[base_method].to_s}").attr('score')
```suggestion
        @xml.xpath("./#{translations_table[base_method]}").attr('score')
```
redundant `.to_s`

2020-09-14 10:10 UTC, sean-yeoh commented on lib/nipper/issue.rb
> +    def respond_to?(method, include_private=false)
```suggestion
    def respond_to?(method, include_private = false)
```
spacing

2020-09-14 10:11 UTC, sean-yeoh commented on lib/nipper/evidence.rb
> +    def respond_to?(method, include_private=false)
```suggestion
    def respond_to?(method, include_private = false)
```
spacing

2020-09-14 10:11 UTC, sean-yeoh commented on lib/nipper/evidence.rb
> +      return @xml.at_xpath('./device').attr(field)
```suggestion
      @xml.at_xpath('./device').attr(field)
```
redundant `return`

2020-09-15 21:21 UTC, rachkor requested changes
I added comments to request a few fields be changed to not have spaces in them. Especially the CVSS score fields! As-is, no one could use the CVSS field names in a filter (you can't filter by "CVSS Score", it has to be spaceless).

2020-09-15 21:21 UTC, rachkor commented on templates/evidence.template
> +#[Device Name]#
```suggestion
#[DeviceName]#
```

2020-09-15 21:21 UTC, rachkor commented on templates/evidence.template
> +#[Device Type]#
```suggestion
#[DeviceType]#
```

2020-09-15 21:21 UTC, rachkor commented on templates/evidence.template
> +#[OS Version]#
```suggestion
#[OS]#
```

2020-09-15 21:21 UTC, rachkor commented on templates/issue.template
> +#[CVSS Base]#
```suggestion
#[CVSSv2.BaseScore]#
```

2020-09-15 21:21 UTC, rachkor commented on templates/issue.template
> +#[CVSS Temporal]#
```suggestion
#[CVSSv2.TemporalScore]#
```

2020-09-15 21:21 UTC, rachkor commented on templates/issue.template
> +#[CVSS Environmental]#
```suggestion
#[CVSSv2.EnvironmentalScore]#
```

2020-09-16 07:38 UTC, etdsoft commented on Gemfile.lock
> +PATH
We don't typically include .lock files in gem repos

2020-09-16 07:38 UTC, etdsoft commented on dradis-nipper.gemspec
> +  spec.license     = 'GPL-2'
Can you please use the standard values we use for other gems (see Okta, or Azure)

2020-09-30 07:58 UTC, merged